### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tiagohm** [tiagohm/mocker#1]
* [ ] Self-hosted usando Docker.
* [ ] Dividido em: Dashboard e API.
* [ ] Apenas um usuário, autenticação através de uma chave secreta (X-Secret-Key).
* [ ] Criar um ou mais Endpoints, agrupando-os por Projeto.
* [ ] Cada Endpoint terá as seguintes features:
   * [ ] Description.
   * [ ] Enable/Disable.
   * [ ] Custom Path.
   * [ ] Method.
   * [ ] Headers.
   * [ ] Response Status.
   * [ ] Content-Type.
   * [ ] Content-Encoding (charset).
   * [ ] Response Body:
     * [ ] Texto (JSON, XML, etc)
     * [ ] Binário (Upload)
     * [ ] Dinâmico (Jinja2, Mustache, etc)
   * [ ] Delay.
* [ ] Suportar subdomínios (o nome do subdomínio será o slug do projeto)
